# Generated by Django 5.2.1 on 2025-06-03 11:28

import Pizza.pizzeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0009_remove_userprofile_age_userprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[Pizza.pizzeria.models.validate_phone], verbose_name='Телефон'),
        ),
    ]
