# Generated by Django 6.0 on 2025-12-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0011_companyinfo_dictionaryterm_employee_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Фото (URL)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото'),
        ),
    ]
