# Generated by Django 5.2.1 on 2025-05-29 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_alter_review_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pizzeria.pizza'),
        ),
    ]
