# Generated by Django 5.2.1 on 2025-06-03 07:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0004_review_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.15'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='cart', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4),
        ),
    ]
