# Generated by Django 5.2.1 on 2025-06-03 07:38

import Pizza.pizzeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0005_alter_coupon_discount_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=17, validators=[Pizza.pizzeria.models.validate_phone], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Часы работы')),
                ('map_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на карту')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной офис')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
